version: "3.9"

services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra-node
    restart: unless-stopped
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_NUM_TOKENS=256
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    volumes:
      - cassandra-data:/var/lib/cassandra

volumes:
  cassandra-data:
    driver: local